ithacaxyz/porto

- README.md
Adds a FAQ section to the readme.md with some initial questions asked on X and TG
> Adds FAQs section to readme

- src/core/Implementation.ts
- src/core/internal/key.ts
- src/core/internal/provider.ts
> feat: restore from storage

- src/core/internal/account.ts
- src/core/internal/delegation.ts
- src/core/internal/implementations/dialog.ts
- src/core/internal/implementations/local.ts
- src/core/internal/key.ts
I added a 10 minute timestamp so when a user authenticates using pin or password, they don't have to enter it every time they are performing a sign action. ( Video for example )
https://github.com/user-attachments/assets/09367921-63a7-4640-ab88-e14b1181b609
> chore: save user verification

- apps/~internal/lib/Porto.ts
- src/core/internal/modes/relay.ts
- test/src/porto.ts
Will need to be chain-aware eventually.
> feat: chain-aware `feeToken`

- .vscode/settings.json
- apps/dialog/src/main.tsx
- apps/dialog/vite.config.ts
- apps/manager/src/main.tsx
- apps/manager/vite.config.ts
currently in development mode sentry makes requests in dialog and manager:
> chore: fully disable sentry in dev

- apps/dialog/src/lib/Hooks.ts
- apps/dialog/src/lib/Price.ts
- apps/dialog/src/lib/Quote.ts
- apps/dialog/src/routes/-components/ActionRequest.tsx
- apps/dialog/src/routes/dialog/eth_sendTransaction.tsx
- apps/dialog/src/routes/dialog/wallet_sendCalls.tsx
- apps/dialog/src/utils.ts
- apps/~internal/lib/Porto.ts
- apps/~internal/lib/Token.tsx
- apps/~internal/lib/index.ts
- src/core/RpcSchema.ts
- src/core/internal/mode.ts
- src/core/internal/modes/contract.ts
- src/core/internal/modes/dialog.ts
- src/core/internal/modes/relay.ts
- src/core/internal/porto.ts
- src/remote/Hooks.ts
Extracts fees from `wallet_prepareCalls` to display in the dialog on Action requests.
Next steps: 
- Sign over the `wallet_prepareCalls` quote/digest.
> feat: fees

- apps/dialog/src/main.tsx
- src/core/internal/modes/dialog.ts
If user is unable to execute with a permissioned key, then we will fall back to the dialog.
> feat: fall back to dialog if invalid session key

- apps/faucet/src/index.ts
- pnpm-workspace.yaml
- wagmi.config.ts
- unused imports,
- update workspaces
> chore: cleanups

- examples/next/.gitignore
- examples/next/README.md
- examples/next/next.config.ts
- examples/next/package.json
- examples/next/src/_generated/contracts.ts
- examples/next/src/app/config.ts
- examples/next/src/app/layout.tsx
- examples/next/src/app/page.tsx
- examples/next/src/app/providers.tsx
- examples/next/tsconfig.json
- examples/vite-react/.gitignore
- examples/vite-react/README.md
- examples/vite-react/index.html
- examples/vite-react/package.json
- examples/vite-react/src/App.tsx
- examples/vite-react/src/_generated/contracts.ts
- examples/vite-react/src/config.ts
- examples/vite-react/src/main.tsx
- examples/vite-react/src/vite-env.d.ts
- examples/vite-react/tsconfig.app.json
- examples/vite-react/tsconfig.json
- examples/vite-react/tsconfig.node.json
- examples/vite-react/vite.config.ts
- pnpm-lock.yaml
- pnpm-workspace.yaml
- src/core/Dialog.ts
- src/core/Porto.ts
- wagmi.config.ts
Wanted to test out some things in Next environment, so added a couple of simple examples in Next and Vite (React).
> feat: examples

- apps/dialog/src/routes/-components/AddFunds.tsx
- apps/docs/wagmi.config.ts
- apps/playground/src/App.tsx
- src/core/Dialog.ts
- src/core/Messenger.ts
- src/core/internal/porto.ts
- src/core/internal/provider.ts
- src/remote/Porto.ts
Ensures the active chain of the Dialog is synced with the App.
> feat: sync active chain

- apps/dialog/src/routeTree.gen.ts
- apps/dialog/src/routes/-components/GrantAdmin.tsx
- apps/dialog/src/routes/dialog/experimental_grantAdmin.tsx
> feat: create grant admin modal

- apps/dialog/src/routeTree.gen.ts
- apps/dialog/src/routes/-components/RevokeAdmin.tsx
- apps/dialog/src/routes/dialog/experimental_revokeAdmin.tsx
- src/remote/Porto.ts
Added a revoke modal to revoke recovery access for the wallet, more details section is left out for now and will be added in soon.
> feat: revoke admin modal

- .github/workflows/deploy-faucet.yml
more reliable detection of whether trigger is `workflow_dispatch`. If true and inputs are invalid we will still get an error so no need to check if input is not empty
> fix: faucet workflow

- apps/dialog/src/routes/-components/GrantAdmin.tsx
- apps/dialog/src/routes/dialog/experimental_grantAdmin.tsx
Added the more details section to the `grantAdmin` modal
> feat: add details section to grant admin modal

- apps/dialog/vite.config.ts
- apps/docs/vocs.config.tsx
- apps/manager/vite.config.ts
- apps/playground/vite.config.ts
- apps/~internal/lib/Env.ts
- apps/~internal/lib/PortoConfig.ts
- src/core/internal/modes/dialog.ts
Align environments with infra docs.
`dev` → odyssey-devnet/relay-dev
`stg` → base-sepolia/relay-staging
`prod` → base-mainnet*/relay
> feat: tweak envs

- .github/workflows/promote-apps.yml
- apps/manager/src/App.tsx
- apps/manager/src/lib/Router.ts
- apps/manager/src/lib/Router.tsx
- apps/manager/src/routes/-components/Intro.tsx
- apps/manager/src/routes/__root.tsx
- apps/manager/src/routes/_layout.recovery.tsx
- apps/manager/vite-env.d.ts
- add way to check if account is auth'd or not. If not then disable some pages,
- remove empty links,
- general cleanup.
> feat: check auth'd status before accessing page

- apps/manager/src/routes/-components/Dashboard.tsx
- use correct tx hash when displaying toast after tx,
- don't clear form when clicking send to show dialog
> fix: send form clearing & toast

- apps/faucet/src/index.ts
- bumb faucet gas,
- specify rpc url
> feat: bump faucet gas

- apps/docs/wagmi.config.ts
- apps/faucet/src/index.ts
- apps/manager/src/hooks/useBlockscoutApi.ts
- apps/manager/src/lib/Constants.ts
- apps/playground/src/App.tsx
- apps/~internal/_generated/contracts.ts
- apps/~internal/lib/PortoConfig.ts
- src/core/Chains.ts
- src/core/internal/modes/dialog.ts
- src/core/internal/provider.test.ts
- test/src/_generated/contracts.ts
- test/src/porto.ts
- wagmi.config.ts
- Adds new dev network.
- Removes Odyssey Testnet as we are no longer using it.
> feat: add new devnet

- .gitattributes
- apps/dialog/src/components/PayButton.tsx
- apps/dialog/src/routeTree.gen.ts
- apps/dialog/src/routes/-components/AddFunds.tsx
- apps/dialog/src/routes/dialog/playground.tsx
- apps/dialog/src/styles.css
- apps/manager/src/styles.css
- apps/~internal/styles/index.css
this change adds some of the onramp views such as Apple Pay, Google Pay and Debit Card. It is not intended as an e2e implementation but only partial. Continuation will happen in more upcoming PRs.
> feat: onramp views

- README.md
https://github.com/DavidAnson/markdownlint/blob/v0.37.4/doc/md014.md
rationale
https://cirosantilli.com/markdown-style-guide/#dollar-signs-in-shell-code
> chore: make commands copy pasteble

- .changeset/bitter-stars-beam.md
- apps/docs/pages/sdk/api/porto/create.mdx
- apps/~internal/lib/PortoConfig.ts
- pnpm-lock.yaml
- pnpm-workspace.yaml
- src/core/Porto.ts
- src/core/internal/delegation.test.ts
- src/core/internal/porto.ts
- src/core/internal/provider.test.ts
- src/core/internal/viem/relay.ts
- test/src/anvil.ts
- test/src/porto.ts
Consolidating the Relay + RPC transport into the one.
> feat: consolidate relay + rpc transports

- apps/docs/pages/rpc-server/wallet_getCallsStatus.md
- apps/docs/vocs.config.tsx
> docs(rpc-server): `wallet_getCallsStatus`

- apps/docs/pages/rpc-server/wallet_health.md
- apps/docs/vocs.config.tsx
On top of #242 
Currently fails because of https://github.com/ithacaxyz/infrastructure/issues/398
> docs(rpc-server): `wallet_health`

- apps/docs/pages/rpc-server/wallet_getCapabilities.md
- apps/docs/vocs.config.tsx
> docs(rpc-server): `wallet_getCapabilities`

- apps/docs/components/Connect.tsx
- apps/manager/src/lib/Wagmi.ts
- apps/manager/src/routes/-components/Landing.tsx
- examples/next/src/app/page.tsx
- examples/vite-react/src/App.tsx
- package.json
- pnpm-lock.yaml
- replace custom `Hooks.useConnect()` porto hook with regular Wagmi `useConnect()` hook,
- replace custom `Hooks.useDisconnect()` porto hook with regular Wagmi `useDisconnect()` hook
> feat: switch to wagmi's useConnect hook

- apps/docs/pages/rpc-server/index.md
- apps/docs/vocs.config.tsx
This is a first draft, after the three remaining methods are documented I'm going to go over them all in a follow up PR. For the overview, I'd like to incorporate some diagrams as well.
> docs(rpc-server): overview

- apps/docs/pages/rpc-server/wallet_prepareCalls.mdx
this is already covered in `<Selectors />`
> docs: rm duplicate selectors

- apps/docs/pages/rpc-server/wallet_verifySignature.mdx
> docs: fix broken links in verifysignature

- apps/docs/pages/rpc-server/wallet_verifySignature.mdx
suggestion, please edit as you see fit
> contains the address of account signature was verified against.
> docs: wording verification

- apps/docs/pages/contracts/account.md
suggestion, please rephrase as you see fit. mainly want to remove "we"
> docs: rephrase recursive calls section

- apps/docs/vocs.config.tsx
> OpenGraph fix

- apps/playground/src/App.tsx
log and display errors from `wallet_connect` to make it easier to see what's happening when visiting from mobile
> chore(playground): log and show connect error

- CLAUDE.md
Adds a CLAUDE.md file to guide Claude Code instances.
> feat: add claude.md

- apps/docs/components/HomePage.tsx
- apps/id/src/routes/-components/Landing.tsx
Adds error handling to docs and id site when email is already verified.
> fix: email verified error handling

- .changeset/little-olives-slide.md
- src/cli/Messenger.ts
- src/cli/internal/commands.ts
- src/cli/internal/context.ts
- src/core/internal/mode.ts
- src/core/internal/modes/contract.ts
- src/core/internal/modes/dialog.ts
- src/core/internal/modes/rpcServer.ts
- src/core/internal/provider.ts
- src/core/internal/typebox/request.ts
- src/core/internal/typebox/rpc.ts
Added functionality to deploy account onchain on `porto onboard --admin-key` command.
> feat(cli): deploy account onchain

- apps/dialog/src/routes/-components/Email.tsx
> feat(dialog): sync email designs

- apps/playground/package.json
- apps/playground/src/main.tsx
- apps/playground/src/vite-env.d.ts
- package.json
- pnpm-lock.yaml
strongly needed in https://github.com/ithacaxyz/porto/pull/516
> feat: add eruda console in playground in dev

- apps/docs/pages/rpc-server/index.md
> Add mainnet rpc server endpoint

- apps/dialog/src/lib/Calls.ts
- apps/dialog/src/lib/FeeTokens.ts
- apps/dialog/src/lib/PermissionsRequest.ts
- apps/dialog/src/routes/-components/ActionRequest.tsx
- apps/dialog/src/routes/-components/GrantAdmin.tsx
- apps/dialog/src/routes/-components/RevokeAdmin.tsx
- apps/dialog/src/routes/-components/RevokePermissions.tsx
- apps/dialog/src/routes/-components/UpdateAccount.tsx
- apps/dialog/src/routes/dialog/eth_sendTransaction.tsx
- apps/dialog/src/routes/dialog/wallet_sendCalls.tsx
- apps/~internal/lib/Query.ts
Refactoring React Query usage to be more complete.
> refactor: react query usage

- apps/dialog/src/lib/Calls.ts
- apps/dialog/src/routes/dialog/eth_sendTransaction.tsx
- apps/dialog/src/routes/dialog/wallet_sendCalls.tsx
> fix: apply `preCalls` in `prepareCalls`

- apps/dialog/src/lib/Dialog.ts
- apps/dialog/src/main.tsx
- src/remote/Events.ts
follows https://github.com/ithacaxyz/porto/pull/631
> pass through origin to initialized event

- apps/dialog/src/routes/-components/ActionRequest.tsx
- apps/playground/src/App.tsx
> feat(next): new action request designs

- apps/docs/pages/sdk/rpc/wallet_getAssets.mdx
- apps/docs/pages/sdk/viem/ServerActions/getAssets.mdx
- apps/docs/pages/sdk/viem/WalletActions/getAssets.mdx
- apps/docs/pages/sdk/wagmi/getAssets.mdx
- apps/docs/pages/sdk/wagmi/useAssets.mdx
- apps/docs/vocs.config.tsx
[`wallet_getAssets` addition](https://github.com/ithacaxyz/porto/pull/617) has been merged to `next` branch.
This PR adds documentation for `wallet_getAssets`.
> feat(docs): `wallet_getAssets` documentation

- apps/dialog/src/routes/-components/ActionRequest.tsx
- apps/dialog/src/routes/-components/Email.tsx
- apps/ui/src/Button/Button.tsx
- Make the `large` size of the button smaller for now, until the dialog layouts become more adapted to bigger button sizes.
- Move from the variant negative to negative-secondary (reject button).
- Remove a fixed button size (so that it adapts automatically).
| before | after |
| ------ | ----- |
| <img width="1844" height="1000" alt="image" src="https://github.com/user-attachments/assets/4ef6ab10-4f78-4e38-825f-cc904c223e72" /> | <img width="1844" height="1000" alt="image" src="https://github.com/user-attachments/assets/bde631c8-92a4-4f74-ab24-fe6ff66a0adf" />|
| <img width="1844" height="1000" alt="image" src="https://github.com/user-attachments/assets/37f7f3e8-dcdd-45f7-b839-a4a972d56374" /> | <img width="1844" height="1000" alt="image" …
> feat: button tweaks

- apps/wagmi/src/contracts.ts
- apps/~internal/_generated/contracts.ts
- examples/authentication-better-auth/src/contracts.ts
- examples/authentication-rainbowkit/src/contracts.ts
- examples/authentication/src/contracts.ts
- examples/next.js/src/contracts.ts
- examples/payments/src/contracts.ts
- examples/permissions/src/contracts.ts
- examples/sponsoring-express/src/contracts.ts
- examples/sponsoring-next.js/src/contracts.ts
- examples/sponsoring-vite/src/contracts.ts
- examples/theming/src/contracts.ts
- examples/vite-react/src/contracts.ts
- scripts/capabilities.ts
- test/src/_generated/contracts.ts
- wagmi.config.ts
this way we don't have to manually update the file when addresses change.
> chore: update addresses in wagmi config

- .changeset/ten-cougars-taste.md
- src/core/internal/provider.ts
Fixes https://ithacaxyz.slack.com/archives/C091V5946DQ/p1755886955347709?thread_ts=1755885943.331629&cid=C091V5946DQ
> fix: rm caching on `eth_requestAccounts`

- apps/ui-playground/src/radix-dark.ts
- apps/ui-playground/src/radix-light.ts
- apps/ui-playground/src/routes/Colors.tsx
> chore: show radix colors on the ui playground

- .changeset/brown-phones-happen.md
- apps/dialog/src/lib/Calls.ts
- apps/dialog/src/routes/-components/ActionRequest.tsx
- apps/dialog/src/routes/-components/Approve.tsx
- apps/dialog/src/routes/-components/SignTypedMessage.tsx
- apps/dialog/src/routes/dialog/eth_sendTransaction.tsx
- apps/dialog/src/routes/dialog/eth_signTypedData_v4.tsx
- apps/playground/src/App.tsx
- src/core/internal/provider.ts
- src/core/internal/schema/rpc.ts
- src/viem/RelayActions.ts
- Refactors ceremony around bundle preparation with a merchant RPC
- Supports `merchantRpcUrl` in `eth_sendTx`
> refactor: refactor merchant bundle preparation; support `merchantRpcUrl` in `eth_sendTx`

- apps/dialog/src/lib/Calls.ts
- apps/playground-interop/src/App.tsx
- src/core/internal/modes/relay.ts
- src/core/internal/requiredFunds.test.ts
- src/core/internal/requiredFunds.ts
- src/core/internal/tokens.ts
Prevously, our "interop" tokens were derived from "fee" tokens, however, an interop token may not be also a fee token.
> refactor: interop tokens

- apps/docs/pages/contracts/account.md
- apps/docs/pages/contracts/benchmarks.mdx
- apps/docs/pages/contracts/bug-bounty.md
- apps/docs/pages/contracts/orchestrator.md
- apps/docs/pages/contracts/security-and-bug-bounty.md
- apps/docs/pages/contracts/security.md
Updated pages for contract changes in the account, bug bounty, security, and benchmarks
> chore: update docs

- apps/dialog/src/routes/-components/ActionRequest.tsx
- apps/dialog/src/routes/-components/Approve.tsx
- apps/dialog/src/routes/-components/Send.tsx
- apps/dialog/src/routes/-components/Swap.tsx
Also fixes a line break issue.
> fix: use native token name, use symbol if token name missing

- .github/workflows/deploy-workers.yml
- apps/service/env.d.ts
- apps/service/src/index.ts
- apps/service/vite.config.ts
- apps/service/wrangler.json
fixes: https://service.porto.workers.dev
note, no users are affected by the error resulted above.
> fix: update service `APP_VERSION`

- src/viem/internal/relayActions.ts
Related https://github.com/ithacaxyz/relay/pull/1392
> refactor: rm fee token required funds

- scripts/relay:up.ts
Update `relay:up` script to also fetch for relevent contract submodules.
> feat(script): sync contract submodules

- apps/dialog/src/routes/__root.tsx
- apps/ui-playground/src/routes/Button.tsx
- apps/ui-playground/src/routes/ButtonArea.tsx
- apps/ui/src/Button/Button.tsx
- apps/ui/src/ButtonArea/ButtonArea.tsx
- apps/ui/src/Frame/Frame.tsx
- Add `Button.Anchor`
- Add `ButtonArea.Anchor`
- `Frame`: add `frameActions` prop
- `Frame`: move to `ButtonArea` for the close button
> feat: add bug button

- src/core/internal/relay/rpcSchema.ts
- src/core/internal/relay/schema/rpc.ts
- src/core/internal/schema/rpc.ts
- src/viem/internal/relayActions.test.ts
- src/viem/internal/relayActions.ts
Adds phone verification methods https://github.com/ithacaxyz/relay/pull/1403
> feat: add phone rpc methods
