.changeset/warm-dingos-hang.md, README.md, examples/wagmi/src/App.tsx, playground/src/App.tsx, pnpm-lock.yaml, pnpm-workspace.yaml, src/Porto.ts, src/actions.ts, src/internal/accountDelegation.ts, src/internal/provider.ts, src/internal/rpcSchema.ts, src/internal/wagmi/core.ts, src/internal/wagmi/react.ts, src/wagmi.ts
Adds ability to import an external account. Supersedes #1.
```mermaid
sequenceDiagram
Consumer ->> Porto: experimental_prepareImportAccount(address)
Porto -->> Consumer: (context, signPayloads)
Consumer ->> Consumer: signatures = sign(signPayloads)
Consumer ->> Porto: experimental_importAccount(context, signatures)
Porto -->> Consumer: (address)
note right of Consumer: connected!
```
=> feat: import external account

README.md
This pull request fixes a broken link in the `README.md` file. The link to the Wagmi documentation was updated to point to the correct URL.
- Fixed `https://wagmi.sh/docs/getting-started` to `https://wagmi.sh/react/getting-started`.
=> fix: broken link README.md

src/core/Dialog.ts, src/core/Messenger.ts, src/remote/Actions.ts
Currently, we _always_ use a popup on Safari as WebKit does [not support WebAuthn credential creation in iframes](https://github.com/WebKit/standards-positions/issues/304).
This PR adds the ability to prefer iframes for RPC methods that do not handle credential creation (e.g. `wallet_sendCalls`), and falls back to a popup if it detects an RPC method that may need credential creation (e.g. `wallet_connect`, `eth_requestAccounts`).
=> feat: safari dialog fallback

.changeset/tasty-cups-speak.md, src/core/Dialog.ts
1Password inserts itself into `<dialog />`, but also marks it `inert`
=> fix: 1password inert attribute

apps/dialog/src/lib/Porto.ts, apps/dialog/src/lib/Router.ts, apps/dialog/src/lib/Wagmi.ts, apps/dialog/src/main.tsx, apps/dialog/src/routes/-components/ActionRequest.tsx, apps/dialog/src/routes/-components/AddFunds.tsx, apps/dialog/src/routes/-components/GrantPermissions.tsx, apps/dialog/src/routes/-components/NotFound.tsx, apps/dialog/src/routes/-components/SignIn.tsx, apps/dialog/src/routes/-components/SignMessage.tsx, apps/dialog/src/routes/__root.tsx, apps/dialog/src/routes/dialog/eth_requestAccounts.tsx, apps/dialog/src/routes/dialog/eth_sendTransaction.tsx, apps/dialog/src/routes/dialog/experimental_addFunds.tsx, apps/dialog/src/routes/dialog/experimental_createAccount.tsx, apps/dialog/src/routes/dialog/experimental_grantPermissions.tsx, apps/dialog/src/routes/dialog/personal_sign.tsx, apps/dialog/src/routes/dialog/wallet_connect.tsx, apps/dialog/src/routes/dialog/wallet_sendCalls.tsx, apps/~internal/lib/Porto.ts, src/core/Dialog.ts, src/core/Messenger.ts, src/remote/Actions.ts, src/remote/Events.ts, src/remote/Porto.ts
Rationale: Some requests we only want to permit on the same origin, or bypass the dialog on the same origin (ie. on `*.porto.sh`). 
Examples: 
- We only want to permit the "Grant Admin" dialog on the same origin, but disallow it on external origins.
- We want to bypass the dialog for connection methods (ie. `wallet_connect`) on the same origin, but show the dialog on external origins.
=> feat: method policies

apps/dialog/src/routes/-components/AddFunds.tsx, src/core/internal/mode.ts, src/core/internal/modes/contract.ts, src/core/internal/modes/dialog.ts, src/core/internal/modes/relay.ts, src/core/internal/provider.test.ts, src/core/internal/provider.ts, src/core/internal/relay.test.ts, src/core/internal/relay/rpcSchema.ts, src/core/internal/relay/typebox/rpc.ts, src/core/internal/viem/relay.test.ts, src/core/internal/viem/relay.ts, src/remote/Porto.ts, test/src/actions.ts
Hooks up `wallet_getCallsStatus` properly internally. Uses Relay `wallet_getCallsStatus` for Relay Mode, and `eth_getTransactionReceipt` for Contract Mode.
=> feat: implement relay `getCallsStatus`

apps/dialog/src/lib/Wagmi.ts, apps/dialog/src/main.tsx, apps/dialog/src/routes/__root.tsx, apps/~internal/lib/PortoConfig.ts, src/core/Dialog.ts, src/core/Porto.ts, src/core/internal/modes/dialog.ts, src/core/internal/provider.ts, src/core/internal/typebox/request.ts, src/remote/Actions.ts, src/remote/Events.ts, src/remote/Porto.ts, src/wagmi/internal/core.ts
Currently, we assume that an App and the Dialog are using the same account. However, this can become out-of-sync for a number of reasons like the user: creating another account from another app, signing out of account from manager, switching account, etc.
This PR ensures that the account coming from the App is always in sync with the Dialog by passing the address + webauthn key such that it can "rehydrate" successfully.
=> fix: sync accounts

.changeset/nine-suits-appear.md, apps/docs/pages/sdk/rpc/experimental_getAccountVersion.mdx, apps/docs/vocs.config.tsx, apps/playground/src/App.tsx, src/core/RpcSchema.ts, src/core/internal/provider.test.ts, src/core/internal/provider.ts, src/core/internal/typebox/request.ts, src/core/internal/typebox/rpc.ts
Adds RPC method to get the current version of an account, and the latest version an account can be upgraded to.
=> feat: `experimental_getAccountVersion`

apps/dialog/src/routes/-components/GrantPermissions.tsx, apps/dialog/src/routes/-components/Permissions.tsx
Updated the `Grant Permission` modal UI to match the Login / Register UI patterns
=> chore: update grant permission modal

apps/dialog/src/components/CheckBalance.tsx, apps/dialog/src/lib/FeeToken.ts, apps/dialog/src/lib/Relay.ts, apps/dialog/src/routes/-components/ActionRequest.tsx, apps/dialog/src/routes/-components/GrantAdmin.tsx, apps/dialog/src/routes/dialog/eth_sendTransaction.tsx, apps/dialog/src/routes/dialog/wallet_sendCalls.tsx, apps/~internal/lib/Query.ts, src/core/internal/account.ts, src/core/internal/mode.ts, src/core/internal/modes/relay.ts, src/core/internal/provider.ts, src/core/internal/relay.ts, src/core/internal/relay/typebox/rpc.ts, src/core/internal/typebox/request.ts
This PR refactors a few things:
- Use new `assetDiff` capability from Relay, instead of our own via `eth_simulateV1`.
- Adds `CheckBalance` HoC to assert if the account has a sufficient balance to pay for fees.
- Refactors `prepareCalls` queries inside `ActionRequest` & `GrantAdmin` into a reusable `usePrepareCalls` Hook.
=> refactor: use asset diffs from relay; misc. refactors

apps/docs/pages/sdk/api/porto/create.mdx, apps/~internal/lib/PortoConfig.ts, src/core/Porto.ts, src/core/RpcServer.test.ts, src/core/internal/mode.ts, src/core/internal/modes/contract.ts, src/core/internal/modes/dialog.ts, src/core/internal/modes/rpcServer.ts, src/core/internal/permissions.ts, src/core/internal/permissionsRequest.ts, src/core/internal/provider.ts, src/remote/Porto.ts, test/src/porto.ts
Fixes a UI issue where an end-user would see the "fee" spend limit added onto the "execution" spend limit (e.g. "11 EXP per day" instead of "10 EXP per day").
=> refactor: permission fee limits

apps/docs/pages/sdk/api/porto/create.mdx, apps/~internal/lib/PortoConfig.ts, src/core/Porto.ts, src/core/RpcServer.ts, src/core/internal/modes/rpcServer.ts, src/core/internal/permissionsRequest.ts, test/src/porto.ts
Fixes a UI issue where an end-user would see the "fee" spend limit added onto the "execution" spend limit (e.g. "11 EXP per day" instead of "10 EXP per day").
=> refactor: permissions fee limit

apps/dialog/src/lib/Wagmi.ts, apps/manager/src/lib/Porto.ts, apps/manager/src/lib/Wagmi.ts, apps/manager/src/routes/-components/Dashboard.tsx, src/wagmi/Connector.ts
Follow up on https://github.com/ithacaxyz/porto/commit/8a484ce1c6a23444eefc200dd97429b76f58519f to avoid extraneous instantiations of Porto. We can rely on Wagmi now.
=> fix(manager): consolidate porto instantiations

apps/docs/pages/rpc-server/snippets/fees.mdx
missing link, we do this for `wallet_getCapabilities` in the next sentence
=> docs: add link to wallet_prepareCalls

apps/docs/pages/sdk/guides/discover-accounts.mdx
Replaced outdated links to the Next.js and Vite example projects with correct paths (examples/next and examples/vite-react) in the Discover Accounts documentation. This ensures users are directed to the actual example folders in the repository.
=> Fix broken example links in Discover Accounts guide

apps/docs/components/HomePage.tsx
This pull request adds bun support to Porto's docs / homepage.
=> docs: add bun support

apps/docs/pages/rpc-server/wallet_getCallsStatus.md, apps/docs/pages/rpc-server/wallet_getCapabilities.md, apps/docs/pages/rpc-server/wallet_getKeys.md, apps/docs/pages/rpc-server/wallet_prepareCalls.mdx, apps/docs/pages/rpc-server/wallet_prepareUpgradeAccount.mdx, apps/docs/pages/rpc-server/wallet_sendPreparedCalls.mdx, apps/docs/pages/rpc-server/wallet_upgradeAccount.md
Uses twoslash to add better types in the RPC server reference. I only converted some of the pages, as the remaining are likely to disappear
=> docs(rpc-server): use twoslash for awesome types

apps/docs/components/HomePage.tsx
=> docs(sdk): add missing space in perms demo

apps/docs/components/Connect.tsx, apps/docs/components/HomePage.tsx
(1) Update "Portal ID":
- Make the "Portal ID" link work for `localhost` too,
- Open ID page in new tab.
(2) Check mint-ability:
- Check NFT minting cost against demo user balance,
- If user has less than what it costs, fund them first.
This can close ithacaxyz/relay#746. Eventually we should also sho display a more scoped message in the dialog where user is given option to "Confirm anyway"
=> fix(docs): check NFT price against balance first

README.md
Fix contracts build instructions, for `demo` and `account` foundry projects.
=> fix: contracts build instructions

.github/workflows/claude.yml
- split jobs into steps, one for PR creation one for PR review,
- added `disallowed_tools`,
- added `direct_prompt` to PR review job
=> feat(ci): split into 2 steps and add disallowed_tools

apps/id/vite.config.ts
Matches https://github.com/ithacaxyz/porto/blob/main/apps/playground/vite.config.ts and https://github.com/ithacaxyz/porto/blob/main/apps/dialog/vite.config.ts so now can all run locally when user runs `SKIP_MKCERT=true pnpm dev`
=> feat(id): add SKIP_MKCERT support for development

src/core/internal/provider.ts, src/server/MerchantRpc.test.ts, src/server/MerchantRpc.ts
Automatically detect merchant RPC server when none is explicitly configured by checking if an endpoint exists at `{hostname}/rpc`.
- Check for merchant RPC at default location (`{hostname}/rpc`) when no URL provided
- Cache detection result in storage to avoid repeated checks  
- Add GET handler to merchant RPC that returns "hello porto" for detection
- Convert relative merchant RPC URLs to absolute URLs
- Remove test for EOA as merchant (no longer relevant)
- `src/core/internal/provider.ts` - Add merchant RPC URL inference logic
- `src/server/MerchantRpc.ts` - Add GET handler for detection
- `src/server/MerchantRpc.test.ts` - Remove obsolete test
=> feat: infer merchant RPC URL from {hostname}/rpc endpoint

.changeset/dry-days-look.md, apps/playground/package.json, apps/playground/vite.config.ts, package.json, pnpm-lock.yaml, src/core/internal/provider.test.ts, src/server/MerchantRpc.test.ts, src/server/MerchantRpc.ts, src/server/internal/requestListener.ts
Added `MerchantRpc.requestListener` method for direct Node.js server integration, eliminating the need for external dependencies like `@mjackson/node-fetch-server`.
- **Added `requestListener` method** to `MerchantRpc` that converts fetch handlers to Node.js-compatible request listeners
- **Implemented internal `requestListener` utility** at `src/server/internal/requestListener.ts` to handle the conversion from fetch handlers to Node.js request listeners
- **Removed dependency** on `@mjackson/node-fetch-server` from both root and playground packages
- **Updated playground** to use the new `requestListener` method instead of the external package
- **Updated tests** to use the new `requestListener` method for consistency
- **Added changeset** documenting the new exported functionality
- …
=> feat: add MerchantRpc.requestListener for Node.js APIs

apps/dialog/src/routes/-components/ActionRequest.tsx
This PR adds protection against malicious merchant RPC servers by simulating asset diffs without the merchant RPC URL when a merchant is present.
- Added a secondary `prepareCallsQuery_assetDiff` query that simulates prepare calls without the merchant RPC URL
- This prevents malicious RPC servers from providing mutated asset diffs to display to end-users
- The original prepare calls query with merchant RPC remains the source of truth for execution
- Only the asset diff display uses the simulated query when a merchant RPC is present
=> feat: simulate asset diff without merchant RPC

.github/workflows/deploy-workers.yml
for a reason I'm currently investigating, whenever https://github.com/ithacaxyz/porto/tree/main/apps/octopus is deployed through the github action, the worker link goes bust and shows 1104 error.
also added a paths filter so that workers are deployed when their files are changed vs. on every push to `main`
=> fix: disable auto-deployment of octopus

.github/workflows/test.yml
Without it test fail, see e.g. https://github.com/ithacaxyz/porto/actions/runs/16122735880
=> fix: use git submodule update in test workflow

.github/workflows/test.yml
another attempt to fix the submodule init issue, plus also adds porto-ref as input since when triggering via repository dispatch we can't specify porto ref like we do when triggering workflows via gh cli / ui
=> fix: resolve submodule checkout failures for arbitrary ref

.changeset/proud-kids-yell.md, src/core/internal/mode.ts, src/core/internal/modes/dialog.ts, src/core/internal/modes/rpcServer.ts, src/core/internal/provider.test.ts, src/core/internal/provider.ts
Resolves https://github.com/ithacaxyz/porto/issues/445.
Fixed an issue where `eth_sendTransaction` was returning a bundle identifier instead of the expected transaction hash.
- Added `asTxHash` parameter to `sendCalls` method in mode interface
- Modified dialog and rpcServer modes to wait for transaction receipt when `asTxHash` is true
- Updated provider to pass `asTxHash: true` for `eth_sendTransaction` calls
- Added proper polling interval (500ms) for `waitForCallsStatus`
- Updated tests to use `waitForTransactionReceipt` instead of `waitForCallsStatus`
- Core internal modules (`src/core/internal/`)
=> fix: return transaction hash instead of bundle id for eth_sendTransaction

.changeset/little-clocks-carry.md, apps/extension/entrypoints/inpage.content.ts, src/core/Chains.ts, src/core/Porto.ts, src/core/internal/mode.ts, src/core/internal/modes/contract.ts, src/core/internal/modes/dialog.ts, src/core/internal/modes/rpcServer.ts, src/viem/ServerClient.ts
Adds a CSP (Content Security Policy) fallback mechanism for the Porto extension that automatically switches from iframe to popup mode when sites block iframe embedding.
- Added event listener in the extension's content script to detect CSP violations
- When a CSP violation blocks Porto's iframe from loading, the extension automatically falls back to popup mode
- Extended dialog mode configuration to preserve the original host configuration during mode switching
- Added fallback RPC URLs to Base and Base Sepolia chains for improved reliability
- Updated Porto's production configuration to use a dedicated storage key
- Extension (`apps/extension`)
- Dialog mode configuration (`src/core/internal/modes/dialog.ts`)
- Chain configurations (`src/core/Chains.ts`)
- …
=> fix: CSP fallback for extension dialog

apps/dialog/src/lib/RpcServer.ts, apps/dialog/src/routes/-components/ActionRequest.tsx, apps/dialog/src/routes/-components/GrantAdmin.tsx, apps/dialog/src/routes/-components/RevokeAdmin.tsx, apps/dialog/src/routes/-components/RevokePermissions.tsx, apps/dialog/src/routes/-components/UpdateAccount.tsx
Refactored the `usePrepareCalls` hook to use React Query's `queryOptions` pattern and added conditional refetch logic to prevent refetching when there is an error.
- Refactored `usePrepareCalls` to use a namespace pattern with `prepareCalls.queryOptions` and `prepareCalls.useQuery`
- Added conditional `refetchInterval` logic that returns `false` when there's an error, preventing unnecessary refetches
- Moved fee token fetching logic into the query function using `Query.client.ensureQueryData`
- Improved type organization and made the API more consistent with other query patterns in the codebase
- Updated all usages of `RpcServer.usePrepareCalls` to use the new `RpcServer.prepareCalls.useQuery` API
=> refactor: refactor `usePrepareCalls` usage, and do not refetch when there is an error

apps/dialog/src/lib/RpcServer.ts, apps/dialog/src/routes/-components/ActionRequest.tsx, apps/dialog/src/routes/dialog/eth_sendTransaction.tsx, apps/dialog/src/routes/dialog/wallet_sendCalls.tsx
Added sign calls functionality to the dialog for `eth_sendTransaction` and `wallet_sendCalls`, enabling proper quote signing with the admin key before sending prepared calls to the RPC server.
- Modified `ActionRequest` component to pass `prepareCalls` data to the `onApprove` callback
- Implemented quote signing logic in `eth_sendTransaction` route:
- Retrieves admin key from account
- Signs the quote digest with the key
- Sends prepared calls with signature
- Returns transaction hash on success
- Implemented quote signing logic in `wallet_sendCalls` route:
- Similar signing flow as eth_sendTransaction
- Returns the full sendPreparedCalls result
- Added type exports in RpcServer module for better type safety
- `src/lib/RpcServer.ts`
- …
=> feat: sign calls from dialog

apps/dialog/src/lib/PermissionsRequest.ts, apps/dialog/src/routes/-components/Email.tsx, apps/dialog/src/routes/-components/SignIn.tsx, apps/dialog/src/routes/-components/SignUp.tsx, apps/dialog/src/routes/dialog/wallet_connect.tsx
Improves the loading experience in the dialog connect flow by distinguishing between data fetching and response states.
- Added initial data to `useResolve` query to prevent unnecessary loading states
- Renamed `loading` prop to `status` with more granular states ('loading' | 'responding')
- Changed from `isPending` to `isFetching` for grant permissions query to better reflect actual loading state
- Disabled form inputs and buttons during the 'loading' state to prevent user interaction while data is being fetched
- Separated loading titles for different actions (signing in vs signing up)
=> feat: tweak connect loading state

.changeset/free-pets-wash.md, apps/playground/src/App.tsx, apps/wagmi/src/App.tsx, src/core/Porto.ts, src/core/RpcSchema.ts, src/core/internal/mode.ts, src/core/internal/modes/dialog.ts, src/core/internal/provider.test.ts, src/core/internal/provider.ts, src/core/internal/schema/request.ts, src/core/internal/schema/rpc.ts, src/core/internal/store.ts, src/remote/Porto.ts, src/remote/internal/methodPolicies.ts
Added support for the `wallet_switchEthereumChain` JSON-RPC method to allow switching between different Ethereum chains.
- Added `wallet_switchEthereumChain` method to RPC schema and request handlers
- Implemented chain switching functionality in dialog and wallet actions
- Updated playground and wagmi examples to demonstrate chain switching
- Added chain change event handling and UI components
- Updated chain configurations to support multiple anvil and porto dev chains
- Playground (`apps/playground`) 
- Wagmi App (`apps/wagmi`)
=> feat: support `wallet_switchEthereumChain`

.changeset/brown-donuts-fail.md, src/remote/Events.ts
I want to use the `MessageEvent.origin` instead of `document.referrer` as a more robust source of truth for the request origin/referrer.
Ideally this would be included in `onInitialized` too but wasn't sure where to put it, especially since there's some overlap in intent with `referrer`.
=> pass through request origin

.changeset/few-wasps-smell.md, src/core/internal/modes/dialog.ts, src/core/internal/schema/capabilities.ts, src/core/internal/siwe.ts
For cases where folks can't use cookies.
=> feat: add `token` property to `signInWithEthereum` capability

apps/theme/export-theme.ts
Add `--as svg` to the `export-theme.ts` script.
=> feat: theme svg export

.changeset/rich-buckets-attack.md, src/core/internal/modes/contract.ts, src/core/internal/modes/rpcServer.ts
When running porto from a RN environment (Hermes) the `location` object on global `window` is not defined. This causes a crash at runtime due to unguarded access to window.location.hostname in `src/core/internal/modes/contract.ts` and `src/core/internal/modes/rpcServer.ts` 
This PR replaces:
`window.location.hostname`
with:
`window.location?.hostname` 
This uses the optional chaining  to safely access `hostname` only when `location` is defined, preventing runtime errors in non-browser environments.
Tested in an Expo + Hermes RN app
=> fix: unguarded access to location.hostname

apps/dialog/src/routes/-components/Layout.tsx, apps/ui/src/Frame/Frame.tsx, apps/ui/src/Screen/Screen.tsx
- Add data-dialog to the Frame component so that the app buttons styles
behave as expected (small radiuses in dialog mode).
- Remove spacing on the Screen component in dialog mode, and let the app
components handle this for now.
- Add padding around IndeterminateLoader.
=> fix: spacing in dialog mode

apps/dialog/src/routes/-components/SignUp.tsx, apps/ui-playground/src/constants.ts, apps/ui-playground/src/routeTree.gen.ts, apps/ui-playground/src/routes/ButtonArea.tsx, apps/ui/src/ButtonArea/ButtonArea.tsx, apps/ui/src/Screen/Screen.tsx, apps/ui/src/index.ts
The `Screen` `bottomAction` prop allows to style its bottom bar-like button (e.g. “Learn about passkeys”) in a way that adapts to the different layouts.
Also improves the focus states & clickable area:
| before | after |
| ------ | ----- |
| <img width=400 src="https://github.com/user-attachments/assets/128b759e-92cc-4d4c-84fa-9d8696341108" /> | <img width=400 src="https://github.com/user-attachments/assets/d827a51d-fd0b-44fd-96cd-3899f66d6677" /> |
- Add a bottomAction prop on the Screen component.
- Add a ButtonArea component (base button surface with focus + active states).
=> feat: screen bottom action

.github/workflows/test.yml, src/core/internal/provider.test.ts, src/viem/ServerActions.test.ts, src/viem/internal/serverActions.test.ts, test/globalSetup.ts, test/src/actions.ts, test/src/chains.ts
Re-enables deployed tests that were previously disabled, switching from staging to production environment and enabling node-based deployment tests.
- Changed default test environment from 'stg' to 'prod' in GitHub workflow
- Re-enabled deployment node tests by removing the `false &&` condition  
- Updated test configuration to use production chains (baseSepolia, optimismSepolia) for both prod and stg environments
- Simplified chain configuration by removing hardcoded internal RPC URLs
- Temporarily skipped interop-related tests (marked with TODO comments) until interop is re-enabled for testnets
- Updated relay configuration and Docker compose setup to use latest relay version (v21.0.1)
- Added timeout in test actions for better test stability
- Updated global test setup to only run Anvil …
=> feat: re-enable deployed tests

.changeset/silent-gifts-attack.md, src/wagmi/Connector.ts
Modified the porto Connector to pass through `chainIds` to `wallet_connect` and removed subsequent switch chain logic.
- Pass `chainIds` array to `wallet_connect` RPC call with requested chainId first, followed by other configured chains
- Remove explicit chain switching logic after connection since chainId is now handled in the initial connect call
- Set `currentChainId` from the response's first chainId
- Improve reconnection logic to fetch both accounts and chainId in parallel
- Add proper error handling when currentChainId is not available
- `porto` Library (`src/`) - Wagmi Connector module
=> feat: pass chainIds to wallet_connect in porto Connector

.changeset/metal-bushes-film.md, src/core/RpcSchema.ts, src/core/internal/mode.ts, src/core/internal/modes/dialog.ts, src/core/internal/modes/relay.ts, src/core/internal/provider.test.ts, src/core/internal/provider.ts, src/core/internal/schema/request.ts, src/core/internal/schema/rpc.ts, src/viem/WalletActions.ts, src/viem/internal/relayActions.test.ts
We don't need to have `wallet_addFaucetFunds` built into the provider as we can call the Relay directly. Less code to maintain :D
=> chore: remove redundant `wallet_addFaucetFunds` provider methods

src/cli/internal/commands.ts
if the user abruptly exists in the middle of the process, it'll still save the key and let them know
test with:
```sh
pnpm dlx https://pkg.pr.new/porto@754 o --admin-key
```
https://github.com/user-attachments/assets/9d5706c1-f69d-4cfc-8b7d-66d39509bded
should mitigate [this situation](https://t.me/porto_devs/2835) in the future.
=> feat(cli): persist admin key immediately to a secure temp file

apps/ui/src/Frame/Frame.tsx
Fixed a style priority issue which was making the close button too wide in dialog mode.
=> fix: close button width

apps/dialog/src/routes/-components/SignTypedMessage.tsx
=> feat: use two levels of depth for the generic typed message view

apps/id/src/App.tsx, apps/id/src/routeTree.gen.ts, apps/id/src/routes/_dash/settings/index.tsx, apps/id/src/routes/_dash/settings/permissions.tsx, apps/id/src/styles.css, pnpm-lock.yaml, pnpm-workspace.yaml, src/wagmi/internal/core.ts, src/wagmi/internal/query.ts, src/wagmi/internal/react.ts
- [#relay 1254](https://github.com/ithacaxyz/relay/pull/1254) updates `wallet_getKeys` (what permissions use under the hood) to be multichain, accepting optional `chainIds` instead of a single `chainId` and returning public keys for all supported chains by default,
- [porto 778](https://github.com/ithacaxyz/porto/pull/778) introduces multichain permissions to core Porto SDK, reflecting the relay change,
- this updates the porto Wagmi hook to match the behavior of `provider.request({ method: 'wallet_getPermissions' })` and wires up multichain permissions data in the new `id` dashboard.
=> feat: new `id` multichain permissions

.changeset/angry-knives-tease.md, src/core/internal/modes/relay.ts, src/viem/Account.ts
- `src/viem/Account.ts`: added optional `webAuthn` to `sign.Parameters` and forward to `Key.sign`.
- `src/core/internal/modes/relay.ts`: passed `webAuthn` through for `signPersonalMessage`, `signTypedData`, and `verifyEmail` actions.
Without passing `webAuthn` down in Relay Actions, `Key.sign` → `WebAuthnP256.sign` uses the default `window.navigator.credentials` on native, causing `Cannot read property 'get' of undefined`.
=> feat: forward `webAuthn` adapters into signing paths on native

.changeset/loud-pens-look.md, src/core/Dialog.ts, src/core/internal/userAgent.ts
https://caniuse.com/mdn-api_permissions_permission_clipboard-write
=> fix: exclude `clipboard-write` permission when firefox

.changeset/silver-squids-brush.md, src/core/internal/modes/relay.ts, src/viem/RelayActions.ts
Fix relay mode functionality by improving account loading and call handling mechanisms.
- Pass keystoreHost to account creation in loadAccounts
- Pass webAuthn object properly in sendCalls
=> fix: relay mode loadAccounts and sendCalls

.changeset/unlucky-hotels-live.md, src/core/internal/mode.ts
When checking for covered calls in a session key, the control flow erroneously falls through when the scope signature is a hex string and the signature matches the call function selector. This causes an error in the next check when the code tries to pass in the scope signature to AbiItem.getSelector which throws an error "Unable to normalize signature." because it's not a valid human-readable function signature.
=> fix: session key validation error

apps/dialog/src/routes/-components/ActionRequest.tsx, apps/dialog/src/routes/-components/Approve.tsx, apps/dialog/src/routes/-components/Send.tsx, apps/dialog/src/routes/-components/Swap.tsx
E2E tests picked up an issue where a user could click "Confirm" on a stale quote. These checks make sure that doesn't happen.
=> feat: tweaks for e2e 

apps/dialog/src/routes/-components/Swap.tsx
Noticed a couple of things were out of alignment with designs while testing, so fixed them.
- Token icon seemed a bit larger than the designs – changed to 20px (same as `Balance` component).
- Swap value not right aligned.
=> tweak: design alignments

src/trusted-hosts.ts
Add postcaptain.xyz to the trusted hosts list to enable iframe dialog rendering for the PostCaptain application.  
- Added `postcaptain.xyz` to the `hostnames` array in `src/trusted-hosts.ts` in alphabetical order  
- This allows PostCaptain users to interact with Porto dialogs via iframe instead of popup fallback  
- Enables secure cross-origin communication between PostCaptain and Porto's dialog system  
=> feat: add postcaptain.xyz to trusted hosts
